<?php
require_once '../config/config.php';
require_once '../config/auth.php';

require_login('teacher');
$teacher_id=(int)$_SESSION['user_id'];
function teacher_count($conn,$sql,$id){$s=$conn->prepare($sql);$s->execute(array($id));return (int)$s->fetchColumn();}
$exam_count=teacher_count($conn,'SELECT COUNT(*) FROM exams WHERE teacher_id=?',$teacher_id);
$question_count=teacher_count($conn,'SELECT COUNT(*) FROM questions WHERE created_by_teacher_id=?',$teacher_id);
$attempt_count=teacher_count($conn,'SELECT COUNT(*) FROM exam_attempts a JOIN exams e ON e.id=a.exam_id WHERE e.teacher_id=? AND a.status IN (\'Submitted\', \'Auto Submitted\')',$teacher_id);
$material_count=teacher_count($conn,'SELECT COUNT(*) FROM study_materials WHERE teacher_id=?',$teacher_id);
$recent=$conn->prepare('SELECT e.title,e.exam_type,e.status,e.starts_at,s.name subject_name FROM exams e LEFT JOIN subjects s ON s.id=e.subject_id WHERE e.teacher_id=? ORDER BY e.created_at DESC LIMIT 6');$recent->execute(array($teacher_id));$recent=$recent->fetchAll(PDO::FETCH_ASSOC);
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Faculty Dashboard | ExamSphere</title><link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css"><link rel="stylesheet" href="../assets/css/portal.css"></head><body class="portal-body"><div class="portal-layout"><?php include 'includes/sidebar.php'; ?><main class="portal-main"><header class="portal-topbar"><div><h1>Good to see you, <?= htmlspecialchars($_SESSION['user_name']) ?></h1><p class="portal-subtitle">Manage your academic content and assess learner progress.</p></div><a class="btn btn-success" href="questions.php"><i class="fa-solid fa-plus me-1"></i> Add Question</a></header><section class="row g-3"><div class="col-md-6 col-xl-3"><div class="metric-card"><div class="metric-icon"><i class="fa-solid fa-file-lines"></i></div><h2><?= $exam_count ?></h2><p>Assigned exams</p></div></div><div class="col-md-6 col-xl-3"><div class="metric-card"><div class="metric-icon"><i class="fa-solid fa-circle-question"></i></div><h2><?= $question_count ?></h2><p>Questions created</p></div></div><div class="col-md-6 col-xl-3"><div class="metric-card"><div class="metric-icon"><i class="fa-solid fa-user-check"></i></div><h2><?= $attempt_count ?></h2><p>Student attempts</p></div></div><div class="col-md-6 col-xl-3"><div class="metric-card"><div class="metric-icon"><i class="fa-solid fa-book-open"></i></div><h2><?= $material_count ?></h2><p>Study materials</p></div></div></section><section class="portal-panel"><div class="d-flex justify-content-between"><h2>Recent assigned exams</h2><a href="exams.php">View all</a></div><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Exam</th><th>Subject</th><th>Type</th><th>Status</th></tr></thead><tbody><?php foreach($recent as $exam): ?><tr><td><?= htmlspecialchars($exam['title']) ?></td><td><?= htmlspecialchars($exam['subject_name'] ?: '—') ?></td><td><?= htmlspecialchars($exam['exam_type']) ?></td><td><span class="badge text-bg-secondary"><?= htmlspecialchars($exam['status']) ?></span></td></tr><?php endforeach; ?><?php if(!$recent): ?><tr><td colspan="4" class="text-center text-muted py-4">No exams have been assigned to you yet.</td></tr><?php endif; ?></tbody></table></div></section></main></div></body></html>
