<?php
require_once '../config/config.php';
require_once '../config/auth.php';

require_login('teacher');
$teacher_id=(int)$_SESSION['user_id'];
$q=$conn->prepare("SELECT e.*,s.name subject_name,COUNT(eq.question_id) question_count FROM exams e LEFT JOIN subjects s ON s.id=e.subject_id LEFT JOIN exam_questions eq ON eq.exam_id=e.id WHERE e.teacher_id=? GROUP BY e.id ORDER BY e.created_at DESC");$q->execute(array($teacher_id));$items=$q->fetchAll(PDO::FETCH_ASSOC);
$practice=count(array_filter($items,function($e){return $e['exam_type']==='Practice';}));$live=count($items)-$practice;
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>My Exams | ExamSphere</title><link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css"><link rel="stylesheet" href="../assets/css/portal.css">
<link rel="stylesheet" href="../assets/css/accessibility.css"></head><body class="portal-body"><div class="portal-layout"><?php include 'includes/sidebar.php'; ?><main class="portal-main"><header class="portal-topbar"><div><h1>My exams</h1><p class="portal-subtitle">Review every practice test and live examination you created.</p></div><a class="btn btn-success" href="create_exam.php"><i class="fa-solid fa-plus me-1"></i>Create Exam</a></header><section class="row g-3"><div class="col-md-4"><div class="metric-card"><div class="metric-icon"><i class="fa-solid fa-file-lines"></i></div><h2><?=count($items)?></h2><p>Total exams</p></div></div><div class="col-md-4"><div class="metric-card"><div class="metric-icon"><i class="fa-solid fa-pen-to-square"></i></div><h2><?=$practice?></h2><p>Practice exams</p></div></div><div class="col-md-4"><div class="metric-card"><div class="metric-icon"><i class="fa-solid fa-tower-broadcast"></i></div><h2><?=$live?></h2><p>Live exams</p></div></div></section><section class="portal-panel"><div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-3"><div><h2 class="h5 mb-1">Exam library</h2><small class="text-muted">Students can only see exams with the exact stored question count.</small></div><input class="form-control" style="max-width:260px" id="examSearch" placeholder="Search title or subject"></div><div class="table-responsive"><table class="table align-middle" id="examTable"><thead><tr><th>Exam</th><th>Subject</th><th>Mode</th><th>Questions</th><th>Marks</th><th>Duration</th><th>Status</th></tr></thead><tbody><?php foreach($items as $i): ?><tr><td><strong><?=htmlspecialchars($i['title'])?></strong><small class="d-block text-muted"><?=htmlspecialchars($i['description']?:'No description')?></small></td><td><?=htmlspecialchars($i['subject_name']?:'—')?></td><td><span class="badge text-bg-<?= $i['exam_type']==='Live'?'warning':'primary' ?>"><?=htmlspecialchars($i['exam_type'])?></span></td><td><?=$i['question_count']?> / <?=$i['required_question_count']?></td><td><?=$i['total_marks']?></td><td><?=$i['duration_minutes']?> min</td><td><span class="badge text-bg-<?=in_array($i['status'],array('Active','Live','Scheduled'))?'success':'secondary' ?>"><?=htmlspecialchars($i['status'])?></span></td></tr><?php endforeach; ?><?php if(!$items): ?><tr><td colspan="7" class="text-center text-muted py-5"><i class="fa-solid fa-file-circle-plus d-block fs-3 mb-2"></i>No exams created yet. Use Create Exam to publish your first test.</td></tr><?php endif; ?></tbody></table></div></section></main></div><script src="assets/js/exams.js" defer></script></body></html>
