<?php
declare(strict_types=1);
require_once '../config/session.php';require_once '../config/config.php';require_once '../config/functions.php';require_once '../config/auth.php';
require_login('student');
$studentId=(int)$_SESSION['user_id'];
function ss_e($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function ss_date($v){if(!$v)return '—';$t=strtotime((string)$v);return $t?date('d M Y',$t):'—';}
try{
 $st=$conn->prepare("SELECT s.id,s.start_date,s.end_date,s.status,p.name AS plan_name,p.duration_months,p.price,p.description,p.benefits FROM subscriptions s INNER JOIN subscription_plans p ON p.id=s.plan_id WHERE s.student_id=? ORDER BY s.start_date DESC,s.id DESC");$st->execute([$studentId]);$subscriptions=$st->fetchAll();
 $plans=$conn->query("SELECT id,name,duration_months,price,description,benefits FROM subscription_plans WHERE status='Active' ORDER BY duration_months ASC,id ASC")->fetchAll();
}catch(Throwable $e){error_log('Student subscriptions failed: '.$e->getMessage());$subscriptions=[];$plans=[];}
$active=null;$today=new DateTimeImmutable('today');
foreach($subscriptions as $s){if($s['status']==='Active' && $s['start_date']<=$today->format('Y-m-d') && $s['end_date']>=$today->format('Y-m-d')){$active=$s;break;}}
include 'includes/navbar.php';
?><style>
.ss-page{min-height:calc(100vh - 70px);padding:38px 0 70px;background:linear-gradient(180deg,#FAF8F0,#F5F5DC);color:#3E2723}.ss-wrap{width:min(1200px,calc(100% - 32px));margin:auto}.ss-hero{padding:42px;border-radius:28px;background:linear-gradient(135deg,#5D4037,#76564B);color:white;box-shadow:0 25px 65px rgba(62,39,35,.16);position:relative;overflow:hidden}.ss-hero:after{content:'';position:absolute;width:260px;height:260px;right:-80px;top:-80px;border-radius:50%;background:rgba(255,255,255,.06)}.ss-k{font-size:9px;letter-spacing:1.6px;font-weight:900;color:#D7C87D}.ss-hero h1{font-size:34px;font-weight:900;margin:9px 0}.ss-hero p{max-width:680px;margin:0;color:#F0E7DF;font-size:12px;line-height:1.8}.ss-active{margin-top:22px;padding:18px;border-radius:18px;background:rgba(255,255,255,.1);border:1px solid rgba(255,255,255,.15);display:flex;justify-content:space-between;gap:15px;align-items:center}.ss-active strong{display:block;font-size:17px}.ss-active small{font-size:9px;color:#E8DDD5}.ss-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin-top:22px}.ss-card{background:#fff;border:1px solid #E3DDD2;border-radius:20px;padding:22px;box-shadow:0 15px 42px rgba(62,39,35,.06);position:relative}.ss-card.best{border-color:#9A9F6B;box-shadow:0 16px 45px rgba(85,107,47,.12)}.ss-card h3{margin:0;color:#3E2723;font-size:20px;font-weight:900}.ss-price{margin:12px 0 5px;color:#556B2F;font-size:30px;font-weight:900}.ss-duration{color:#7F756D;font-size:9px}.ss-desc{color:#6F6861;font-size:10px;line-height:1.7;min-height:55px;margin-top:10px}.ss-benefits{margin:14px 0 0;padding:0;list-style:none}.ss-benefits li{padding:6px 0;border-bottom:1px solid #F0EBE4;color:#5C544E;font-size:9px}.ss-badge{position:absolute;right:16px;top:16px;padding:5px 9px;border-radius:999px;background:#EEF3E7;color:#556B2F;font-size:7px;font-weight:900}.ss-note{margin-top:20px;padding:16px 18px;border:1px dashed #D6CBBE;border-radius:16px;background:#FBF8F0;color:#6F6861;font-size:9px;line-height:1.7}.ss-history{margin-top:22px;background:#fff;border:1px solid #E3DDD2;border-radius:20px;padding:20px}.ss-history h2{font-size:15px;font-weight:900;color:#3E2723;margin:0 0 14px}.ss-table{width:100%;border-collapse:collapse}.ss-table th,.ss-table td{text-align:left;padding:11px;border-bottom:1px solid #EEE9E1;font-size:9px}.ss-table th{background:#FAF7F1;color:#6F6861;text-transform:uppercase}.ss-status{font-size:8px;font-weight:900;padding:5px 8px;border-radius:999px}.ss-status.active{background:#EEF4E7;color:#4F672D}.ss-status.expired{background:#FFF3DB;color:#89651E}.ss-status.cancelled{background:#FBEDEB;color:#9F4D45}@media(max-width:900px){.ss-grid{grid-template-columns:1fr 1fr}.ss-hero{padding:28px}.ss-active{flex-direction:column;align-items:flex-start}}@media(max-width:620px){.ss-grid{grid-template-columns:1fr}.ss-wrap{width:calc(100% - 18px)}.ss-hero h1{font-size:27px}}
</style><main class="ss-page"><div class="ss-wrap"><section class="ss-hero"><div class="ss-k"><i class="fa-solid fa-crown"></i> EXAMSPHERE MEMBERSHIP</div><h1>Subscription Access</h1><p>ExamSphere subscriptions are managed by the administration team. Your active membership controls access to subscription-required live examinations and subscription-only study material.</p><?php if($active):?><div class="ss-active"><div><small>Current active plan</small><strong><?=ss_e($active['plan_name'])?></strong></div><div><small>Valid until</small><strong><?=ss_date($active['end_date'])?></strong></div><div><small>Status</small><strong>Active</strong></div></div><?php endif;?></section><section class="ss-grid"><?php foreach($plans as $i=>$p):?><article class="ss-card <?=($i===count($plans)-1?'best':'')?>"><?php if($i===count($plans)-1):?><span class="ss-badge">BEST VALUE</span><?php endif;?><h3><?=ss_e($p['name'])?></h3><div class="ss-price">₹<?=number_format((float)$p['price'],2)?></div><div class="ss-duration"><?= (int)$p['duration_months']?> month(s) access</div><div class="ss-desc"><?=ss_e($p['description']??'')?></div><ul class="ss-benefits"><?php foreach(preg_split('/
|
|
/',(string)($p['benefits']??'')) as $benefit): if(trim($benefit)==='')continue;?><li><i class="fa-solid fa-circle-check" style="color:#556B2F;margin-right:6px"></i><?=ss_e(trim($benefit))?></li><?php endforeach;?></ul></article><?php endforeach;?></section><div class="ss-note"><i class="fa-solid fa-shield-halved" style="color:#556B2F;margin-right:7px"></i><strong>Admin-managed activation:</strong> Online payment is currently disabled. An administrator assigns or changes subscriptions from the Admin Subscription Management panel.</div><?php if($subscriptions):?><section class="ss-history"><h2>Subscription History</h2><div style="overflow:auto"><table class="ss-table"><thead><tr><th>Plan</th><th>Start</th><th>End</th><th>Status</th></tr></thead><tbody><?php foreach($subscriptions as $s):?><tr><td><?=ss_e($s['plan_name'])?></td><td><?=ss_date($s['start_date'])?></td><td><?=ss_date($s['end_date'])?></td><td><span class="ss-status <?=strtolower($s['status'])?>"><?=ss_e($s['status'])?></span></td></tr><?php endforeach;?></tbody></table></div></section><?php endif;?></div></main></body></html>
